seata:
  enabled: true
  enable-auto-data-source-proxy: true
  service:
    disable-global-transaction: false

server:
  port: 8901

spring:
  application:
    name: seata-tm
  cloud:
    alibaba:
      seata:
        tx-service-group: my_test_tx_group
    config:
      enabled: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #    url: jdbc:mysql://10.35.227.217:3306/seata_tm?zeroDateTimeBehavior=convertToNull&amp;useUnicode=true&amp;characterEncoding=utf-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    #    username: mysql
    #    password: R7VuVj4M
    #    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.74.130:3306/seata_tm?serverTimezone=GMT%2B8&characterEncoding=utf8&useUnicode=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: dahuacloud
    type: com.alibaba.druid.pool.DruidDataSource
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200


#seata:
#  enableAutoDataSourceProxy: true
#  enabled: true
#  enable-auto-data-source-proxy: true
#  service:
#    vgroup_mapping:
#      my_test_tx_group: default
#    grouplist:
#      default: 127.0.0.1:8091
#    enable-degrade: false
#    disable-global-transaction: false
#  config:
#    type: file
#    file:
#      name: file.conf
#  registry:
#    type: file
#    file:
#      name: file.conf



mybatis-plus:
  # 如果是放在src/main/java目录下 classpath:/com/yourpackage/*/com.exchange.mapper/*Mapper.com.exchange.mapper
  # 如果是放在resource目录 classpath:/com.exchange.mapper/*Mapper.com.exchange.mapper
  mapper-locations: classpath:mapper/**/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.dahua.seata.entities
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    #若采用雪花算法生成id，需要在生成的实体类中将id的type = IdType.AUTO去掉
    id-type: 0
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    #refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    # Sequence序列接口实现类配置
    #逻辑删除配置（下面3个配置）
    logic-delete-value: Y
    logic-not-delete-value: N
    #sql-injector: com.nky.pork.quality.standard.conf.MybatisPlusConfig
    configuration:
      #配置返回数据库(column下划线命名&&返回java实体是驼峰命名)，自动匹配无需as（没开启这个，SQL需要写as： select user_id as userId）
      map-underscore-to-camel-case: true
      cache-enabled: false
      #配置JdbcTypeForNull, oracle数据库必须配置
      jdbc-type-for-null: 'null'

eureka:
  instance:
    prefer-ip-address: true
    metadata-map:
      version: v7
  client:
    serviceUrl:
      defaultZone: http://user:123456@${EUREKA:eureka7001.com}:7001/eureka/ #注册中心地址:
